name: Docker Image CI

on:
  push:
    branches: [ "main" ]
    tags:
      - "*"
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Configure docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ghcr.io/mia-platform/documentation
          tags: |
            type=ref,event=branch
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
          labels: |
            org.opencontainers.image.documentation=https://mia-platform.eu
            org.opencontainers.image.vendor=Mia-Platform
      - name: Display Docker metadata
        run: |
          echo "Docker image: ${{ steps.meta.outputs.images }}"
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"
          echo "BUILDTIME=${{fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created']}}"
          echo "VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}"

    
